name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Module 0.2
      id: module-0-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 0.2
        setup-command: ''
        command: python3 check.py "Module 0.2"
        timeout: 10
    - name: Module 1.0
      id: module-1-0
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 1.0
        setup-command: ''
        command: python "*1.0*"
        timeout: 10
    - name: Module 1.1
      id: module-1-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 1.1
        setup-command: ''
        command: python check.py "*1.1*"
        timeout: 10
    - name: Module 1.2
      id: module-1-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 1.2
        setup-command: ''
        command: python check.py "*1.2*"
        timeout: 10
    - name: Module 1.3
      id: module-1-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 1.3
        setup-command: ''
        command: python check.py "*1.3*"
        timeout: 10
    - name: Module 2.0
      id: module-2-0
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 2.0
        setup-command: ''
        command: python check.py "*2.0*"
        timeout: 10
    - name: Module 2.1
      id: module-2-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 2.1
        setup-command: ''
        command: python check.py "*2.1*"
        timeout: 10
    - name: Module 2.2
      id: module-2-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 2.2
        setup-command: ''
        command: python check.py "*2.2*"
        timeout: 10
    - name: Module 2.3
      id: module-2-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 2.3
        setup-command: ''
        command: python check.py "*2.3*"
        timeout: 10
    - name: Module 2.4
      id: module-2-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 2.4
        setup-command: ''
        command: python check.py "*2.4*"
        timeout: 10
    - name: Module 3.0
      id: module-3-0
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 3.0
        setup-command: ''
        command: python check.py "*3.0*"
        timeout: 10
    - name: Module 3.1
      id: module-3-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 3.1
        setup-command: ''
        command: python check.py "*3.1*"
        timeout: 10
    - name: Module 3.2
      id: module-3-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 3.2
        setup-command: ''
        command: python check.py "*3.2*"
        timeout: 10
    - name: Module 3.3
      id: module-3-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 3.3
        setup-command: ''
        command: python check.py "*3.3*"
        timeout: 10
    - name: Module 3.4
      id: module-3-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 3.4
        setup-command: ''
        command: python check.py "*3.4*"
        timeout: 10
    - name: Module 4.0
      id: module-4-0
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 4.0
        setup-command: ''
        command: python check.py "*4.0*"
        timeout: 10
    - name: Module 4.1
      id: module-4-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 4.1
        setup-command: ''
        command: python check.py "*4.1*"
        timeout: 10
    - name: Module 4.2
      id: module-4-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 4.2
        setup-command: ''
        command: python check.py "*4.2*"
        timeout: 10
    - name: Module 4.3
      id: module-4-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 4.3
        setup-command: ''
        command: python check.py "*4.3*"
        timeout: 10
    - name: Module 4.4
      id: module-4-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Module 4.4
        setup-command: ''
        command: python check.py "*4.4*"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MODULE-0-2_RESULTS: "${{steps.module-0-2.outputs.result}}"
        MODULE-1-0_RESULTS: "${{steps.module-1-0.outputs.result}}"
        MODULE-1-1_RESULTS: "${{steps.module-1-1.outputs.result}}"
        MODULE-1-2_RESULTS: "${{steps.module-1-2.outputs.result}}"
        MODULE-1-3_RESULTS: "${{steps.module-1-3.outputs.result}}"
        MODULE-2-0_RESULTS: "${{steps.module-2-0.outputs.result}}"
        MODULE-2-1_RESULTS: "${{steps.module-2-1.outputs.result}}"
        MODULE-2-2_RESULTS: "${{steps.module-2-2.outputs.result}}"
        MODULE-2-3_RESULTS: "${{steps.module-2-3.outputs.result}}"
        MODULE-2-4_RESULTS: "${{steps.module-2-4.outputs.result}}"
        MODULE-3-0_RESULTS: "${{steps.module-3-0.outputs.result}}"
        MODULE-3-1_RESULTS: "${{steps.module-3-1.outputs.result}}"
        MODULE-3-2_RESULTS: "${{steps.module-3-2.outputs.result}}"
        MODULE-3-3_RESULTS: "${{steps.module-3-3.outputs.result}}"
        MODULE-3-4_RESULTS: "${{steps.module-3-4.outputs.result}}"
        MODULE-4-0_RESULTS: "${{steps.module-4-0.outputs.result}}"
        MODULE-4-1_RESULTS: "${{steps.module-4-1.outputs.result}}"
        MODULE-4-2_RESULTS: "${{steps.module-4-2.outputs.result}}"
        MODULE-4-3_RESULTS: "${{steps.module-4-3.outputs.result}}"
        MODULE-4-4_RESULTS: "${{steps.module-4-4.outputs.result}}"
      with:
        runners: module-0-2,module-1-0,module-1-1,module-1-2,module-1-3,module-2-0,module-2-1,module-2-2,module-2-3,module-2-4,module-3-0,module-3-1,module-3-2,module-3-3,module-3-4,module-4-0,module-4-1,module-4-2,module-4-3,module-4-4
